# /usr/lib/tmpfiles.d/aither-license-lifecycle.conf -- aither-license-lifecycle(7).
# The motd fragment directory, and the license state directory (same line as
# aither-license.conf; tmpfiles treats the duplicate as idempotent).
d /run/motd.d 0755 root root -
d /var/lib/aither 0755 root root -
d /var/lib/aither/license 0700 root root -
