"""awnix-theme -- one theme file, every surface of the desktop.

    awnix-theme list                 the installed themes (* marks the current one)
    awnix-theme current              the current theme's id
    awnix-theme set <id> [--no-reload]
    awnix-theme next                 cycle to the next theme (Super+Shift+T)
    awnix-theme pick                 choose from a launcher menu (Super+T)
    awnix-theme ensure               render the default if nothing is rendered yet
    awnix-theme render <id> <dir>    render into a directory, reload nothing
    awnix-theme validate [--themes DIR] [--templates DIR]
    awnix-theme --self-test

A theme is ONE TOML file in /usr/share/awnix/themes/<id>.toml. `set` renders every
template in /usr/share/awnix/theme-templates/ with it -- Hyprland, waybar, the launcher
(fuzzel), mako, the terminal (foot), GTK, the lock screen, an awkit CSS-variables file --
plus a gradient wallpaper PNG, into ~/.config/awnix/theme/, then reloads whatever of
those is running. Placeholders are {{section.key}} with an optional filter:

    {{colors.bg}}            #0b1020        {{colors.bg|hex}}      0b1020
    {{colors.bg|hypr}}       rgb(0b1020)    {{colors.bg|hypra:ee}} rgba(0b1020ee)
    {{colors.bg|rgba:0.9}}   rgba(11, 16, 32, 0.9)
    {{paths.wallpaper}}      supplied by the engine, never by a theme

An unknown key or filter is an ERROR, never an empty string: a half-rendered config is
a desktop that starts with the wrong colours and says nothing.

Exit: 0 ok * 1 failed / violation * 2 could not judge (no themes, unreadable file).
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import zlib
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from . import TomlError, config_home, load_toml, loads_toml, templates_dir, themes_dir

DEFAULT_THEME = "aither-dark"
MARKER = "GENERATED by awnix-theme"

#: target key -> template file name (also the output name). The wallpaper is not a text
#: template; it is rendered from the theme's [wallpaper] table by render_wallpaper().
TARGETS: Dict[str, str] = {
    "hyprland": "hyprland.conf",
    "waybar": "waybar.css",
    "launcher": "fuzzel.ini",
    "mako": "mako.conf",
    "terminal": "foot.ini",
    "gtk": "gtk.css",
    "gtk_settings": "gtk-settings.ini",
    "lock": "swaylock.conf",
    "awkit": "awkit.css",
}
WALLPAPER = "wallpaper.png"
#: Keys the engine supplies. A theme may not define them and a template may use them.
ENGINE_KEYS = ("paths.wallpaper", "paths.theme_dir")

PLACEHOLDER = re.compile(r"\{\{\s*([A-Za-z0-9_.]+)\s*(?:\|\s*([A-Za-z]+)(?::([^}\s]+))?\s*)?\}\}")
HEX = re.compile(r"^#[0-9a-fA-F]{6}$")


class ThemeError(ValueError):
    """A theme or template that cannot be rendered. Exit 1."""


class DeadError(RuntimeError):
    """Could not judge (no themes installed, unreadable directory). Exit 2."""


# ── loading ───────────────────────────────────────────────────────────────────────


def theme_ids(tdir: Optional[Path] = None) -> List[str]:
    d = tdir or themes_dir()
    if not d.is_dir():
        raise DeadError(f"no themes directory at {d}")
    ids = sorted(p.stem for p in d.glob("*.toml"))
    if not ids:
        raise DeadError(f"no themes in {d}")
    return ids


def load_theme(tid: str, tdir: Optional[Path] = None) -> Dict[str, Any]:
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", tid):
        raise ThemeError(f"not a theme id: {tid!r}")
    path = (tdir or themes_dir()) / f"{tid}.toml"
    if not path.is_file():
        raise ThemeError(f"no such theme {tid!r} (have: {', '.join(theme_ids(tdir))})")
    try:
        return load_toml(path)
    except TomlError as exc:
        raise ThemeError(f"{path.name}: {exc}") from None


def flatten(data: Dict[str, Any], prefix: str = "") -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for k, v in data.items():
        key = f"{prefix}{k}"
        if isinstance(v, dict):
            out.update(flatten(v, key + "."))
        else:
            out[key] = v
    return out


def template_keys(text: str) -> List[str]:
    return sorted({m.group(1) for m in PLACEHOLDER.finditer(text)})


def load_templates(tpl_dir: Optional[Path] = None) -> Dict[str, str]:
    d = tpl_dir or templates_dir()
    out: Dict[str, str] = {}
    for key, fname in TARGETS.items():
        p = d / fname
        if not p.is_file():
            raise DeadError(f"template for {key!r} missing: {p}")
        out[key] = p.read_text(encoding="utf-8")
    return out


# ── rendering ─────────────────────────────────────────────────────────────────────


def _rgb(value: str) -> Tuple[int, int, int]:
    if not isinstance(value, str) or not HEX.match(value):
        raise ThemeError(f"not a #rrggbb colour: {value!r}")
    return int(value[1:3], 16), int(value[3:5], 16), int(value[5:7], 16)


def _apply(key: str, value: Any, flt: Optional[str], arg: Optional[str]) -> str:
    if flt is None:
        if isinstance(value, bool):
            return "true" if value else "false"
        return str(value)
    if flt == "hex":
        _rgb(value)
        return value[1:].lower()
    if flt == "hypr":
        _rgb(value)
        return f"rgb({value[1:].lower()})"
    if flt == "hypra":
        _rgb(value)
        if not arg or not re.fullmatch(r"[0-9a-fA-F]{2}", arg):
            raise ThemeError(f"{key}|hypra needs a two-hex-digit alpha, got {arg!r}")
        return f"rgba({value[1:].lower()}{arg.lower()})"
    if flt == "rgb":
        r, g, b = _rgb(value)
        return f"{r}, {g}, {b}"
    if flt == "rgba":
        r, g, b = _rgb(value)
        try:
            a = float(arg or "")
        except ValueError:
            raise ThemeError(f"{key}|rgba needs an alpha 0..1, got {arg!r}") from None
        if not 0.0 <= a <= 1.0:
            raise ThemeError(f"{key}|rgba alpha out of range: {a}")
        return f"rgba({r}, {g}, {b}, {a:g})"
    raise ThemeError(f"unknown filter |{flt} on {key}")


def render(text: str, theme: Dict[str, Any], paths: Optional[Dict[str, str]] = None) -> str:
    flat = flatten(theme)
    for k, v in (paths or {}).items():
        flat[f"paths.{k}"] = v

    def sub(m: "re.Match[str]") -> str:
        key, flt, arg = m.group(1), m.group(2), m.group(3)
        if key not in flat:
            raise ThemeError(f"template uses {{{{{key}}}}}, which the theme does not define")
        return _apply(key, flat[key], flt, arg)

    out = PLACEHOLDER.sub(sub, text)
    if "{{" in out:
        raise ThemeError("a malformed {{placeholder}} survived rendering")
    return out


def _png_chunk(kind: bytes, data: bytes) -> bytes:
    return (struct.pack(">I", len(data)) + kind + data
            + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF))


def render_wallpaper(theme: Dict[str, Any], width: int = 1920, height: int = 1080) -> bytes:
    """A vertical gradient top -> bottom with a soft horizon band of `glow`. Stdlib PNG."""
    wp = theme.get("wallpaper") or {}
    try:
        top, bottom, glow = _rgb(wp["top"]), _rgb(wp["bottom"]), _rgb(wp["glow"])
    except KeyError as exc:
        raise ThemeError(f"[wallpaper] needs {exc.args[0]}") from None
    rows = []
    horizon = 0.62
    for y in range(height):
        t = y / max(1, height - 1)
        c = [top[i] + (bottom[i] - top[i]) * t for i in range(3)]
        d = abs(t - horizon)
        w = max(0.0, 1.0 - d / 0.18) ** 2 * 0.22
        c = [int(round(c[i] * (1 - w) + glow[i] * w)) for i in range(3)]
        rows.append(b"\x00" + bytes(c) * width)
    raw = b"".join(rows)
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + _png_chunk(b"IHDR", ihdr)
            + _png_chunk(b"IDAT", zlib.compress(raw, 6)) + _png_chunk(b"IEND", b""))


def render_all(tid: str, out_dir: Path, *, tdir: Optional[Path] = None,
               tpl_dir: Optional[Path] = None, wallpaper_size: Tuple[int, int] = (1920, 1080)
               ) -> Dict[str, Path]:
    """Render every target into out_dir atomically (write to a temp name, then rename)."""
    theme = load_theme(tid, tdir)
    templates = load_templates(tpl_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = {"wallpaper": str(out_dir / WALLPAPER), "theme_dir": str(out_dir)}
    rendered = {key: render(text, theme, paths) for key, text in templates.items()}
    png = render_wallpaper(theme, *wallpaper_size)
    written: Dict[str, Path] = {}
    for key, text in rendered.items():
        written[key] = _atomic_write(out_dir / TARGETS[key], text.encode("utf-8"))
    written["wallpaper"] = _atomic_write(out_dir / WALLPAPER, png)
    _atomic_write(out_dir / "current", (tid + "\n").encode("utf-8"))
    return written


def _atomic_write(path: Path, data: bytes) -> Path:
    tmp = path.with_name(f".{path.name}.tmp")
    tmp.write_bytes(data)
    os.replace(tmp, path)
    return path


# ── validation (the checker and the self-test share it) ────────────────────────────


def validate(tdir: Path, tpl_dir: Path) -> List[str]:
    """Every theme defines every key every template uses, and every template renders."""
    problems: List[str] = []
    try:
        templates = load_templates(tpl_dir)
    except DeadError as exc:
        return [str(exc)]
    used = sorted({k for t in templates.values() for k in template_keys(t)})
    needed = [k for k in used if k not in ENGINE_KEYS]
    for tid in theme_ids(tdir):
        try:
            theme = load_theme(tid, tdir)
        except ThemeError as exc:
            problems.append(f"{tid}: {exc}")
            continue
        flat = flatten(theme)
        for k in needed:
            if k not in flat:
                problems.append(f"{tid}: does not define {k} (used by a template)")
        for k in flat:
            if k.startswith("paths."):
                problems.append(f"{tid}: defines {k}, which only the engine supplies")
        if not str(theme.get("name", "")).strip():
            problems.append(f"{tid}: no name")
        paths = {"wallpaper": "/x/wallpaper.png", "theme_dir": "/x"}
        for key, text in templates.items():
            try:
                render(text, theme, paths)
            except ThemeError as exc:
                problems.append(f"{tid}: template {key} does not render: {exc}")
        try:
            render_wallpaper(theme, 8, 8)
        except ThemeError as exc:
            problems.append(f"{tid}: wallpaper does not render: {exc}")
    return problems


# ── applying to the running session ─────────────────────────────────────────────────


def out_dir() -> Path:
    return config_home() / "awnix" / "theme"


def current(base: Optional[Path] = None) -> Optional[str]:
    p = (base or out_dir()) / "current"
    try:
        v = p.read_text(encoding="utf-8").strip()
    except OSError:
        return None
    return v or None


def _link_user_file(path: Path, text: str) -> None:
    """Write an app's user config ONLY if absent or ours -- never clobber a user's file."""
    try:
        existing = path.read_text(encoding="utf-8")
    except OSError:
        existing = None
    if existing is not None and MARKER not in existing:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write(path, text.encode("utf-8"))


def install_user_links(od: Path) -> None:
    home = config_home()
    _link_user_file(home / "foot" / "foot.ini",
                    f"# {MARKER}: the terminal follows the awnix theme.\n"
                    f"# Replace this file to take foot over yourself.\n"
                    f"[main]\ninclude={od / TARGETS['terminal']}\n")
    for gtk in ("gtk-3.0", "gtk-4.0"):
        _link_user_file(home / gtk / "gtk.css", (od / TARGETS["gtk"]).read_text(encoding="utf-8"))
        _link_user_file(home / gtk / "settings.ini",
                        (od / TARGETS["gtk_settings"]).read_text(encoding="utf-8"))


def _run(argv: List[str]) -> None:
    if shutil.which(argv[0]):
        try:
            subprocess.run(argv, check=False, timeout=10,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except (OSError, subprocess.TimeoutExpired) as exc:
            # The files are already rendered; a failed reload leaves the old colours
            # on screen until the next login, so say so and carry on.
            print(f"awnix-theme: reload step {argv[0]} failed: {exc}", file=sys.stderr)


def reload_running(od: Path, theme: Dict[str, Any]) -> None:
    if os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
        _run(["hyprctl", "reload"])
    _run(["pkill", "-SIGUSR2", "-x", "waybar"])
    _run(["makoctl", "reload"])
    if shutil.which("swaybg") and os.environ.get("WAYLAND_DISPLAY"):
        _run(["pkill", "-x", "swaybg"])
        try:
            subprocess.Popen(["swaybg", "-m", "fill", "-i", str(od / WALLPAPER)],
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                             start_new_session=True)
        except OSError as exc:
            print(f"awnix-theme: cannot restart swaybg: {exc}", file=sys.stderr)
    gtk = theme.get("gtk") or {}
    scheme = "prefer-dark" if gtk.get("prefer_dark") else "default"
    _run(["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", scheme])
    if gtk.get("theme"):
        _run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", str(gtk["theme"])])
    if gtk.get("icons"):
        _run(["gsettings", "set", "org.gnome.desktop.interface", "icon-theme", str(gtk["icons"])])
    _run(["notify-send", "-a", "awnix", "-t", "2500", "Theme", str(theme.get("name", ""))])


def apply(tid: str, *, reload: bool = True) -> Path:
    od = out_dir()
    render_all(tid, od)
    install_user_links(od)
    if reload:
        reload_running(od, load_theme(tid))
    return od


def next_id(ids: List[str], cur: Optional[str]) -> str:
    if cur not in ids:
        return DEFAULT_THEME if DEFAULT_THEME in ids else ids[0]
    return ids[(ids.index(cur) + 1) % len(ids)]


def pick(ids: List[str], cur: Optional[str]) -> Optional[str]:
    names = {tid: str(load_theme(tid).get("name", tid)) for tid in ids}
    lines = [f"{'* ' if tid == cur else '  '}{names[tid]}  ({tid})" for tid in ids]
    cfg = out_dir() / TARGETS["launcher"]
    argv = ["fuzzel", "--dmenu", "--prompt=theme > "]
    if cfg.is_file():
        argv.insert(1, f"--config={cfg}")
    try:
        r = subprocess.run(argv, input="\n".join(lines), capture_output=True,
                           text=True, encoding="utf-8", errors="replace", timeout=300)
    except (OSError, subprocess.TimeoutExpired):
        return None
    m = re.search(r"\(([a-z0-9-]+)\)\s*$", r.stdout.strip())
    return m.group(1) if m else None


# ── self-test ──────────────────────────────────────────────────────────────────────


def _default_src() -> Tuple[Path, Path]:
    """Installed dirs if present, else the source tree beside this package."""
    here = Path(__file__).resolve().parent.parent
    t, p = themes_dir(), templates_dir()
    if t.is_dir() and p.is_dir():
        return t, p
    return here / "themes", here / "templates"


def self_test() -> int:
    fails = 0

    def chk(cond: bool, label: str) -> None:
        nonlocal fails
        print(f"  {'ok  ' if cond else 'FAIL'} {label}")
        if not cond:
            fails += 1

    tdir, tpl = _default_src()
    try:
        ids = theme_ids(tdir)
    except DeadError as exc:
        print(f"awnix-theme self-test: cannot judge: {exc}")
        return 2
    chk(len(ids) >= 4 and DEFAULT_THEME in ids, f"at least 4 themes incl. {DEFAULT_THEME}: {ids}")
    chk(validate(tdir, tpl) == [], "every theme defines every template key and renders")

    # The TOML reader agrees with tomllib on every shipped theme (where tomllib exists).
    try:
        import tomllib
    except ImportError:
        tomllib = None  # type: ignore[assignment]
    for tid in ids:
        text = (tdir / f"{tid}.toml").read_text(encoding="utf-8")
        mini = loads_toml(text, force_mini=True)
        if tomllib is not None:
            chk(mini == tomllib.loads(text), f"{tid}: mini TOML reader == tomllib")
        else:
            chk(bool(mini.get("colors")), f"{tid}: mini TOML reader parses it")

    theme = load_theme(DEFAULT_THEME, tdir)
    chk(render("{{colors.bg|hypra:ee}}", {"colors": {"bg": "#0B1020"}}) == "rgba(0b1020ee)",
        "hypra filter")
    chk(render("{{colors.bg|rgba:0.5}}", {"colors": {"bg": "#0b1020"}}) == "rgba(11, 16, 32, 0.5)",
        "rgba filter")

    def raises(fn) -> bool:
        try:
            fn()
        except ThemeError:
            return True
        return False

    chk(raises(lambda: render("{{colors.nope}}", theme)), "an undefined key is an error")
    chk(raises(lambda: render("{{colors.bg|bogus}}", theme)), "an unknown filter is an error")
    chk(raises(lambda: render("{{name|hex}}", theme)), "a non-colour through |hex is an error")
    chk(raises(lambda: load_theme("../etc/passwd", tdir)), "a path-like theme id is refused")

    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        # A theme missing a key the templates use must FAIL validation.
        bad_t = tdp / "themes"
        bad_t.mkdir()
        src = (tdir / f"{DEFAULT_THEME}.toml").read_text(encoding="utf-8")
        (bad_t / "broken.toml").write_text(
            re.sub(r"(?m)^accent\s*=.*$", "", src, count=1), encoding="utf-8")
        chk(any("colors.accent" in p for p in validate(bad_t, tpl)),
            "a theme missing colors.accent fails validation")
        # A template naming a key no theme has must FAIL validation.
        bad_p = tdp / "tpl"
        shutil.copytree(tpl, bad_p)
        (bad_p / TARGETS["mako"]).write_text("x={{colors.nonexistent}}\n", encoding="utf-8")
        chk(any("nonexistent" in p for p in validate(tdir, bad_p)),
            "a template using an undefined key fails validation")
        # Rendering writes every target, the wallpaper and `current`.
        od = tdp / "out"
        written = render_all(DEFAULT_THEME, od, tdir=tdir, tpl_dir=tpl, wallpaper_size=(64, 36))
        chk(set(written) == set(TARGETS) | {"wallpaper"}, "every target rendered")
        chk(all(p.stat().st_size > 0 for p in written.values()), "no empty output")
        chk(current(od) == DEFAULT_THEME, "current records the theme")
        png = (od / WALLPAPER).read_bytes()
        chk(png.startswith(b"\x89PNG\r\n\x1a\n") and b"IEND" in png[-12:], "wallpaper is a PNG")
        chk(all("{{" not in p.read_text(encoding="utf-8") for k, p in written.items()
                if k != "wallpaper"), "no placeholder survives")
        chk(str(od / WALLPAPER) in (od / TARGETS["lock"]).read_text(encoding="utf-8"),
            "the lock screen points at the rendered wallpaper")
        # User files: written when absent, NEVER over a user's own file.
        prev_cfg = os.environ.get("XDG_CONFIG_HOME")
        os.environ["XDG_CONFIG_HOME"] = str(tdp / "cfg")
        (tdp / "cfg" / "gtk-4.0").mkdir(parents=True)
        (tdp / "cfg" / "gtk-4.0" / "gtk.css").write_text("/* mine */\n", encoding="utf-8")
        install_user_links(od)
        chk("include=" in (tdp / "cfg" / "foot" / "foot.ini").read_text(encoding="utf-8"),
            "foot.ini includes the theme")
        chk((tdp / "cfg" / "gtk-4.0" / "gtk.css").read_text(encoding="utf-8") == "/* mine */\n",
            "a user's own gtk.css is left alone")
        chk(MARKER in (tdp / "cfg" / "gtk-3.0" / "gtk.css").read_text(encoding="utf-8"),
            "an absent gtk.css is written")
        if prev_cfg is None:
            os.environ.pop("XDG_CONFIG_HOME", None)
        else:
            os.environ["XDG_CONFIG_HOME"] = prev_cfg
    chk(next_id(["a", "b", "c"], "c") == "a" and next_id(["a", "b"], "a") == "b",
        "next cycles and wraps")
    chk(next_id(ids, None) == DEFAULT_THEME, "next from nothing lands on the default")

    print(f"awnix-theme self-test: {'PASS' if not fails else f'FAIL ({fails})'}")
    return 0 if not fails else 1


# ── CLI ────────────────────────────────────────────────────────────────────────────


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(prog="awnix-theme", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--list-verbs", action="store_true")
    sub = ap.add_subparsers(dest="cmd")
    sub.add_parser("list")
    sub.add_parser("current")
    s = sub.add_parser("set")
    s.add_argument("theme")
    s.add_argument("--no-reload", action="store_true")
    sub.add_parser("next")
    sub.add_parser("pick")
    sub.add_parser("ensure")
    r = sub.add_parser("render")
    r.add_argument("theme")
    r.add_argument("dir")
    v = sub.add_parser("validate")
    v.add_argument("--themes", default=None)
    v.add_argument("--templates", default=None)
    a = ap.parse_args(argv)

    if a.self_test:
        return self_test()
    if a.list_verbs:
        print("\n".join(["list", "current", "set", "next", "pick", "ensure", "render", "validate"]))
        return 0
    try:
        if a.cmd == "list":
            cur = current()
            for tid in theme_ids():
                name = load_theme(tid).get("name", tid)
                print(f"{'*' if tid == cur else ' '} {tid:<20} {name}")
            return 0
        if a.cmd == "current":
            cur = current()
            print(cur or DEFAULT_THEME)
            return 0
        if a.cmd == "set":
            apply(a.theme, reload=not a.no_reload)
            print(f"theme: {a.theme}")
            return 0
        if a.cmd == "next":
            tid = next_id(theme_ids(), current())
            apply(tid)
            print(f"theme: {tid}")
            return 0
        if a.cmd == "pick":
            tid = pick(theme_ids(), current())
            if not tid:
                return 1
            apply(tid)
            print(f"theme: {tid}")
            return 0
        if a.cmd == "ensure":
            cur = current()
            ids = theme_ids()
            tid = cur if cur in ids else DEFAULT_THEME
            if cur != tid or not (out_dir() / TARGETS["hyprland"]).is_file():
                apply(tid, reload=False)
            return 0
        if a.cmd == "render":
            render_all(a.theme, Path(a.dir))
            return 0
        if a.cmd == "validate":
            tdir = Path(a.themes) if a.themes else themes_dir()
            tpl = Path(a.templates) if a.templates else templates_dir()
            problems = validate(tdir, tpl)
            for p in problems:
                print(f"awnix-theme: {p}", file=sys.stderr)
            return 1 if problems else 0
        ap.print_help()
        return 2
    except ThemeError as exc:
        print(f"awnix-theme: {exc}", file=sys.stderr)
        return 1
    except DeadError as exc:
        print(f"awnix-theme: {exc} -- NOT VERIFIED", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
